# No compression, faster
# https://yarnpkg.com/configuration/yarnrc#compressionLevel
compressionLevel: 0

# Use user-global cache instead of project-local cache in ".yarn/cache"
# https://yarnpkg.com/configuration/yarnrc#enableGlobalCache
enableGlobalCache: true

# Print build output to terminal during "yarn install"
# https://yarnpkg.com/configuration/yarnrc#enableInlineBuilds
enableInlineBuilds: true

# Disable postinstall scripts
# https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false

# Disable yarn telemetry
# https://yarnpkg.com/configuration/yarnrc#enableTelemetry
enableTelemetry: false

# Behave like Yarn Classic and NPM
# https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules

# Token to use when accessing NPM registry
# https://yarnpkg.com/configuration/yarnrc#npmAuthToken
npmAuthToken: "${PANDELL_NPM_TOKEN}"

# Yarn binary location
# https://yarnpkg.com/configuration/yarnrc#yarnPath
yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Fix transitive peer dependencies warnings in yarn 4.3.0+
# For more info see "PR#6205: Rework peer requirement and warning system",
# https://github.com/yarnpkg/berry/pull/6205
# https://yarnpkg.com/configuration/yarnrc#packageExtensions
packageExtensions:
  "@eslint-react/ast@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } }
  "@eslint-react/core@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } }
  "@eslint-react/shared@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } }
  "@eslint-react/var@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } }
  "@tanstack/eslint-plugin-query@*": { peerDependencies: { "typescript": ">= 5" } }
  "eslint-plugin-import-x@*": { peerDependencies: { "typescript": ">= 5" } }
  "eslint-plugin-testing-library@*": { peerDependencies: { "typescript": ">= 5" } }
